title: Things i do not want to forget
description: > # this means to ignore newlines until "baseurl:"


permalink: ":title/"
baseurl: ""
url: "https://blog.bilka.sk"

# Author Settings
author: Jozef Bilka
author-img: author.jpg
about-author: I just need a place to store things, i do not want to forget.

# Tracker
analytics: UA-46512356-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
